chore: add embedded type form components
grindery-io/grindery-wallet pull request #10
Opened 2024-02-07 12:40 UTC by juniormp

2024-02-07 23:50 UTC, milukove requested changes

2024-02-07 23:50 UTC, milukove commented on src/components/pages/FormPage/FormPage.tsx
> +          user_name: user.userName,
@juniormp Let's add user id as well?

2024-02-07 23:50 UTC, milukove commented on src/components/pages/FormPage/FormPage.tsx
> +    axios
Let's extract this api call to a separate file in `/src/services` folder? See other files there for examples.

2024-02-07 23:50 UTC, milukove commented on src/components/pages/FormPage/FormPage.tsx
> +  useEffect(() => {
When doing async requests inside `useEffect`, I prefer to add a controller, to handle abortion when component unmounts. For example:
* https://github.com/grindery-io/grindery-wallet/blob/main/src/components/pages/ActivityPage.tsx#L36
* https://github.com/grindery-io/grindery-wallet/blob/main/src/components/pages/ActivityPage.tsx#L56-L58

This makes sure there are no memory leaks or unhandled responses.

2024-02-08 12:09 UTC, juniormp commented on src/components/pages/FormPage/FormPage.tsx
> +          user_name: user.userName,
Sure, btw the paras are in underscore case because its the only patter Typeform allows.

2024-02-08 18:44 UTC, milukove approved these changes

2024-02-08 18:44 UTC, merged